### ISSUE TITLE
[Epic] Data Augmentation Issue Overview and Discussions

### ISSUE THREAD

**Issue by tianjianjiang** [bigscience-workshop/promptsource#55]
@tianjianjiang (Mike) hopes that this issue ticket will act like an Epic issue that covers potential tasks of data augmentation.
Please kindly note that Mike is merely the first member who tries to work on data augmentation and by no means an authority of this topic. Feel free to participate in any possible way.

# Issues (PRs)
- #10 (#19)
- #49

# Request for Proposal
Although the section title is https://en.wikipedia.org/wiki/Request_for_proposal but this section isn't anywhere near a formal RFP yet. Please don't hesitate to edit or comment.

## Purpose
Diversify our prompts and generalize our models.
(For example, see this comment: https://github.com/bigscience-workshop/promptsource/pull/52#issuecomment-853346673.)

## Scopes
1. Prompt template
2. (Possibly in the future) perturbation or more complex approaches for training/fine-tuning, e.g., papers of prompt/prefix tuning.

#### Expected input/output in Jinja
Presumably `world politics`, `sports`, `business`, and `science and technology` must remain intact.
* Input
```jinja
{{text}} 
Is this a piece of news regarding world politics, sports, business, or science and technology? ||| 
{{ ["World politics", "Sports", "Business", "Science and technology"][label] }}
```
* Output
```jinja
{{text}} 
Is this news about world politics, sports, business, or science and technology? ||| 
{{ ["World politics", "Sports", "Business", "Science and technology"][label] }}
```

#### TBD
- [ ] Input/output formats for a shared API
  - [ ] Jinja compatibility; on-going discussions (Mike was hoping that we can use https://docs.github.com/en/discussions but no strong preference here):
         1. https://github.com/bigscience-workshop/promptsource/issues/49#issuecomment-852319484
         2. https://github.com/bigscience-workshop/promptsource/issues/49#issuecomment-852324510 
         3. https://github.com/bigscience-workshop/promptsource/issues/49#issuecomment-852379349
  - [ ] Streamlit UI behavior
  - [ ] Template PR flow
- [ ] Different strategies (e.g, back-translation, summarization, https://github.com/makcedward/nlpaug, https://github.com/QData/TextAttack, etc.)
  - [ ] Integration test

**Comment by VictorSanh** [comment]
this plan looks good to me!

Since we are in agreement that protecting text with jinja is a good solution (https://github.com/bigscience-workshop/promptsource/issues/49#issuecomment-853902299) let's go with that.

we can discuss directly on issues/pull requests. I'll take a closer look at your PR later today.

(note that we'll start the prompt sourcing sprint independently of the augmentation pipeline since it's almost two orthogonal and // questions)

**Comment by stephenbach** [comment]
Closing due to inactivity. Feel free to reopen if you want to revisit this!
